//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Hieu_Quy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_MUC_SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANH_MUC_SAN_PHAM()
        {
            this.SAN_PHAM_CHI_TIET = new HashSet<SAN_PHAM_CHI_TIET>();
        }
    
        public int MaDanhMuc { get; set; }
        public string TenDangMuc { get; set; }
        public string AnhDanhMuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAN_PHAM_CHI_TIET> SAN_PHAM_CHI_TIET { get; set; }
    }
}
