//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Hieu_Quy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINH_ANH
    {
        public int MaHinhAnh { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<bool> AnhChinh { get; set; }
    
        public virtual SAN_PHAM_CHI_TIET SAN_PHAM_CHI_TIET { get; set; }
    }
}
