//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Hieu_Quy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Web_CosmeticsEntities : DbContext
    {
        public Web_CosmeticsEntities()
            : base("name=Web_CosmeticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BINH_LUAN> BINH_LUAN { get; set; }
        public virtual DbSet<CHUC_VU> CHUC_VU { get; set; }
        public virtual DbSet<DANH_MUC_SAN_PHAM> DANH_MUC_SAN_PHAM { get; set; }
        public virtual DbSet<HINH_ANH> HINH_ANH { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<HOA_DON_CHI_TIET> HOA_DON_CHI_TIET { get; set; }
        public virtual DbSet<SAN_PHAM_CHI_TIET> SAN_PHAM_CHI_TIET { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<VOUCHER> VOUCHERs { get; set; }
    }
}
