//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Hieu_Quy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM_CHI_TIET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN_PHAM_CHI_TIET()
        {
            this.BINH_LUAN = new HashSet<BINH_LUAN>();
            this.HINH_ANH = new HashSet<HINH_ANH>();
            this.HOA_DON_CHI_TIET = new HashSet<HOA_DON_CHI_TIET>();
        }
    
        public int MaSP { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public string HinhAnhChinh { get; set; }
        public Nullable<decimal> GiaGoc { get; set; }
        public string MoTaChiTiet { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string TenSanPham { get; set; }
        public bool IsHome { get; set; }
        public bool IsSale { get; set; }
        public Nullable<decimal> PhanTramSale { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINH_LUAN> BINH_LUAN { get; set; }
        public virtual DANH_MUC_SAN_PHAM DANH_MUC_SAN_PHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINH_ANH> HINH_ANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON_CHI_TIET> HOA_DON_CHI_TIET { get; set; }
    }
}
